# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-31 20:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20171031_2024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='time',
            new_name='creation_time',
        ),
    ]
