# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-31 21:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20171031_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='creation_time',
        ),
    ]
