# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-01 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_visitor_creation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='days',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='creation_time',
            field=models.CharField(default='2017-11-01 18:19:07', max_length=250),
        ),
    ]
