# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20171102_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='creation_time',
            field=models.CharField(default='2017-11-02 17:59:40', max_length=250),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='days',
            field=models.CharField(default=6, max_length=10),
        ),
    ]
